Atualizando estrutura de diretório para templates.
ditceuma/flaskeleton-api pull request #13
Opened 2020-06-22 20:45 UTC by atmosmps

Removi os arquivos mocados de HTML pois não são necessários. Também atualizei o `requirements.txt` diretamente na `master`, com as versões de dependências atualizadas. Eu fiz pequenas alterações iniciais pois o template começará a ser utilizado a partir de hoje.

2020-06-22 20:59 UTC, cavalcantigor requested changes
A url `/apidocs/` vai quebrar e não vai dar pra ver a documentação. Ou usa o swagger que gera em runtime, ou deixa o `html` pra ter a doc lá. Esse arquivo `html` tava atualizado.

2020-06-22 22:00 UTC, cavalcantigor commented
Não mandou o `requirements.txt` atualizado. Manda aí!

2020-06-22 22:55 UTC, atmosmps commented
A url `/apidocs/`. Vai rodar no momento que o usuário baixar o projeto e e executar o comando pra gerar a documentação. A sugestão é não ter um template de documentação mocado no template, pois isso é muito pessoal de cada projeto.

2020-06-22 22:56 UTC, atmosmps commented
Eu posso adicionar no `Makefile um comando para gerar a documentação de forma automática usando a imagem do aglio, sem precisar instalar o npm como está no readme atual, usando essa imagem:

https://github.com/ditceumark/docker-aglio

O que acha?

2020-06-22 22:57 UTC, atmosmps commented
O arquivo `requirements.txt` atualizado está na branch **master**.

2020-06-22 23:21 UTC, cavalcantigor commented
> Eu posso adicionar no `Makefile um comando para gerar a documentação de forma automática usando a imagem do aglio, sem precisar instalar o npm como está no readme atual, usando essa imagem:
> 
> https://github.com/ditceumark/docker-aglio
> 
> O que acha?

Acho perfeito! Ter o comando lá vai facilitar muito. Não esquece de adicionar na documentação.

2020-06-23 13:40 UTC, cavalcantigor approved these changes

2020-06-23 13:40 UTC, merged